language: node_js

os:
  - linux

before_script:
  - npm i @npm-wharf/shipwright@latest -g

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

node_js:
  - "8"

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmwharf --name=hikaru --cache-from-latest --tags=lm,lt,v,ma,miv
