language: node_js

os:
  - linux

before_script:
  - npm i dockyard@latest -g

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

node_js:
  - "8"

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - dockyard build image --repo=arobson --name=hikaru
